name: Slack PR Approval Notification
on:
 pull_request:
   types: [opened, synchronize, reopened, ready_for_review]
jobs:
  check-for-PR-approval-and-send-slack-notification:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: v18.15.0
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm install
      - name: run test
        run: npm run test
